<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
    'login/process',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();

echo $this->form()->openTag($form);
 
echo $this->formCollection($form);

echo $this->form()->closeTag();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
      
		echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}

echo "

	<form>
		<div class=\"row\">
			<div class=\"col-md-4\"></div>
			<div class=\"col-md-4\">
				<div class=\"form-group\">
					<label for=\"exampleInputEmail1\">Adresse mail</label>
					<input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" placeholder=\"Email\">
				</div>
			</div>
			<div class=\"col-md-4\"></div>
		</div>
		<div class=\"row\">
			<div class=\"col-md-4\"></div>
			<div class=\"col-md-4\">
				<div class=\"form-group\">
					<label for=\"exampleInputPassword1\">Mot de passe</label>
					<input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" placeholder=\"Mot de Passe\">
				</div>
			</div>
			<div class=\"col-md-4\"></div>
		</div>
		<div class=\"col-md-4\"></div>
		<div class=\"col-md-4\">
			<div class=\"checkbox\">
				<label><input type=\"checkbox\">Se rapeller de moi ?</label>
			</div>
			<button type=\"submit\" class=\"btn btn-default\">Se connecter</button>
		</div>
		<div class=\"col-md-4\"></div></div>
	</form>

";