 <?php
 // module/Restaurant/view/restaurant/restaurant/delete.phtml:

 $url = $this->url('restaurant', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 

 
  
 <form action="<?php echo $url; ?>" method="post">

	 <input type="hidden" name="id" value="<?php echo (int) $restaurant->id; ?>" />
	 
	 <div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<h1>Supprimer un restaurant</h1>
			<div class="bs-callout bs-callout-danger">
				<div class="apanel-body"> 
					<p>Voulez-vous supprimer votre critique sur le restaurant 
					 <?php echo $this->escapeHtml($restaurant->name); ?>, 
					 <?php echo $this->escapeHtml($restaurant->address); ?> ?
					</p>
				
					<input class="btn btn-danger" type="Oui" value="Supprimer" name="del">
					<input class="btn btn-default" type="Non" value="Annuler" name="del">

				</div>
			</div>
		</div>
		<div class="col-md-3"></div>
	</div>
</form>