 <?php
 // module/Restaurant/view/restaurant/restaurant/index.phtml:

 $title = 'Mes restaurants';
 $this->headTitle($title);
 ?>
 <h1>
	<?php echo $this->escapeHtml($title); ?>
	<a class="btn btn-primary" style="float:right;"  role="button" href="<?php echo $this->url('restaurant', array('action'=>'add'));?>">Ajouter un restaurant</a>
 </h1>
 


 <table class="table">
 <tr>
     <th>Nom</th>
     <th>Adresse</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($restaurants as $restaurant) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($restaurant->name);?></td>
     <td><?php echo $this->escapeHtml($restaurant->address);?></td>
     <td>
         <a href="<?php echo $this->url('restaurant',
             array('action'=>'edit', 'id' => $restaurant->id));?>">Éditer</a>
         <a href="<?php echo $this->url('restaurant',
             array('action'=>'delete', 'id' => $restaurant->id));?>">Supprimer</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>