 <?php
 // module/Friend/view/friend/friend/index.phtml:

 $title = 'Mes amis';
 $this->headTitle($title);
 ?>
 <h2><?php echo $this->escapeHtml($title); ?></h2>


 <div class="row">
  <div class="col-md-12"><h3>Nom<h3></div>
 </div>
	 <?php foreach ($friends as $friend) : ?>
	 <div class=\"page-header\">
		<div class="row">
			<div class="col-md-12" style="font-size:18px;"><a href="<?php echo $this->url('friend', array('action'=>'index', 'id' => $friend->id));?>"> <?php echo $friend->real_name; ?></a></div>
		</div>
	 </div>
	 <?php endforeach; ?>


<h2>Personnes m'ayant ajouté</h2>
<div class="row">
  <div class="col-md-6"><h3>Nom<h3></div>
  <div class="col-md-6"><h3>Action<h3></div>
 </div>

<?php foreach ($requests as $request) : ?>
<div class=\"page-header\">
	<div class="row">
	
	<div class="col-md-6"style="font-size:18px;"><?php echo $request->real_name; ?></div>
	
	<div class="col-md-6" style="font-size:18px;"><a href="<?php echo $this->url('friend',
	 array('action'=>'add', 'id' => $request->id));?>">Accepter</a></div>
	</div>
	</div>
<?php endforeach; ?>
	 
 
 
 