 <?php

 $title = 'Invitations';
 $this->headTitle($title);
 ?>
 

<div class="row">
	<div class="col-md-2">

		<h1>&nbsp;</h1>
		
		<ul class="nav nav-pills nav-stacked">
		  <li role="presentation" class="active"><a href="/invitations">Invitations</a></li>
		  <li role="presentation"><a href="/">Timeline</a></li>
		  <li role="presentation"><a href="/me">Vos flicks</a></li>
		</ul>
		
	
	</div>

	<div class="col-md-7">
	
		<h1>Mes invitations</h1>

		<table class="table">
		<?php
		if(count($invitations) == 0)
			echo '<tr><td>Vous n\'avez aucune invitation</td></tr>';
		?>
		<?php foreach ($invitations as $invitation) : ?>

		<tr>
			<td>@<?php echo $invitation->nickname; ?></td>
			<td><a class="btn btn-primary" href="/friend/add/<?php echo $invitation->id; ?>" role="button" style="float:right;">Ajouter aux amis</a></td>
		</tr>
		  
		<?php endforeach; ?>
		

		</table>
		
	</div>
	<div class="col-md-3">

				<h1>Mes amis </h1>

				<form class="form-inline" method="POST" name="friend" action="/search" id="friend">
					<div class="form-group">
						<input type="text" name="name" class="form-control" id="exampleInputEmail3" value="<?php echo ($searchterm === 0) ? "" : $searchterm; ?>" placeholder="Chercher quelqu'un">
					</div>
					<button type="submit" name="submit" class="btn btn-primary">
						<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
					</button>
				</form>	
				
				<div id="friendlist">
					<?php foreach ($friends as $friend) : ?>
						<div><a href="<?php echo $this->url('user', array('action'=>'index', 'id' => $friend->nickname));?>">@<?php echo $friend->nickname;?></a></div>
					<?php endforeach; ?>
				</div>

	</div>
</div>