<?php

 $title = 'Recherche';
 $this->headTitle($title);
 ?>
 

<div class="row">
	<div class="col-md-2">

		<h1>&nbsp;</h1>
		
		<ul class="nav nav-pills nav-stacked">
		  <li role="presentation" class="active"><a href="">Recherche</a></li>
		  <li role="presentation"><a href="./">Timeline</a></li>
		  <li role="presentation"><a href="./me">Vos flicks</a></li>
		</ul>
		
	
	</div>

	<div class="col-md-7">
	
		<h1>Recherche</h1>
		
		<?php
		if(count($users) == 0) {
			echo '<div class="alertblock"><img src="../img/ship.png" /><span>Personne à l\'horizon !</span><span>Votre recherche n\'a pas été fructueuse.</span></div>';
		}
		else {
		?>

		<table class="table usergrid">	
		<?php foreach ($users as $user) :  ?>

		<tr>
			<td>
				<?php 
					echo '<a href="./user/'.$user["nickname"].'">@'.$user["nickname"].'</a>';
				?>
			</td>
			<td>
				<?php 
					echo '<a class="btn btn-primary" href="../user/'. $user["nickname"] .'" role="button" style="float:right;">Voir le profil</a>';
				?>
				
			
			
			</td>
		</tr>
		  
		<?php endforeach; ?>
		</table>
		<?php } ?>
		
	</div>
	<div class="col-md-3">

				<h1>Mes amis </h1>


				<form class="form-inline" method="POST" name="friend" action="./search" id="friend">
					<div class="form-group">
						<input type="text" name="name" class="form-control" id="exampleInputEmail3" value="<?php echo ($searchterm === 0) ? "" : $searchterm; ?>" placeholder="Chercher quelqu'un">
					</div>
					<button type="submit" name="submit" class="btn btn-primary">
						<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
					</button>
				</form>		
				
				<div id="friendlist">
					<?php foreach ($friends as $friend) : ?>
						<div><a href="<?php echo $this->url('user', array('action'=>'index', 'id' => $friend->nickname));?>">@<?php echo $friend->nickname;?></a></div>
					<?php endforeach; ?>
				</div>

	</div>
</div>