<?php
 // module/Flick/view/flick/flick/add.phtml:

 $this->headTitle("Modifier un flickr");
 ?>
 <h1><?php echo $this->escapeHtml("Modifier un flick"); ?></h1>
 <?php
 
 // var_dump($form->get('mark'));
 $form->setAttribute('action', $this->url('flick', array('action' => 'edit', 'id' => $id, 'class'=>'form-horizontal')));
 $form->prepare();
  
   echo $this->form()->openTag($form);
   echo $this->formHidden($form->get('id'));
   
 ?>
 

 

<div class="row">
	<div class="col-md-6">
		<div id="ref" class="bs-callout bs-callout-primary">
			<div class="apanel-body">
			
				

				<div class="form-group">
					<label for="field_name" class="col-sm-3 control-label">Titre</label>
					<div class="col-sm-9">
						
						<?php	echo $this->formRow($form->get('name')); ?>
					</div>
				</div>

				<div class="form-group">
					<label for="field_comment" class="col-sm-3 control-label">Commentaire</label>
					<div class="col-sm-9">
						<?php	echo $this->formRow($form->get('comment')); ?>
					</div>
				</div>

				<div class="form-group">
					<label for="nothing" class="col-sm-3 control-label">Note</label>
					<div class="col-sm-9">

						<div class="btn-group star-group" role="group" aria-label="...">
							
							<button type="button" name="1" class="mark btn btn-default"> <span class="glyphicon glyphicon-star<?php echo ($form->get('mark')->getValue() < 1) ? "-empty" : ''; ?>" aria-hidden="true"></span></button>
							<?php	echo $this->formHidden($form->get('mark')); ?>
							<button type="button" name="2" class="mark btn btn-default"> <span class="glyphicon glyphicon-star<?php echo ($form->get('mark')->getValue() < 2) ? "-empty" : ''; ?>" aria-hidden="true"></span></button>
							<button type="button" name="3" class="mark btn btn-default"> <span class="glyphicon glyphicon-star<?php echo ($form->get('mark')->getValue() < 3) ? "-empty" : ''; ?>" aria-hidden="true"></span></button>
							<button type="button" name="4" class="mark btn btn-default"> <span class="glyphicon glyphicon-star<?php echo ($form->get('mark')->getValue() < 4) ? "-empty" : ''; ?>" aria-hidden="true"></span></button>
							<button type="button" name="5" class="mark btn btn-default"> <span class="glyphicon glyphicon-star<?php echo ($form->get('mark')->getValue() < 5) ? "-empty" : ''; ?>" aria-hidden="true"></span></button>
						</div>
						
						<?php	echo $this->formElementErrors($form->get("mark"), array('class' => "")) ?>
					</div>
				</div>

				<div class="form-group">
					<label for="nothing" class="col-sm-3 control-label">Addresse</label>
					<div class="col-sm-9">
						<?php	echo $this->formRow($form->get('address')); ?>
					</div>
				</div>

				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
						<?php	echo $this->formSubmit($form->get('submit')); ?>
					</div>
				</div>

			</div>
		</div>

	</div>

	<div class="col-md-6">
	
		<input type="hidden" name="search" value="">

		<input id="pac-input" class="controls" type="text" placeholder="Entrez une adresse">

		<div id="map" style="height:325px;width:100%;margin:20px 0;"></div>

		<script async defer src="https://maps.googleapis.com/maps/api/js?callback=initMap&libraries=places"></script>

	</div>
</div>


<?php
 echo $this->form()->closeTag();
?>