 <?php
 // module/Sign/view/sign/sign/add.phtml:

  $this->headTitle("Inscription");


 $form->setAttribute('action', $this->url('sign', array('action' => 'index')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 
 
?>
<div class="row">

			<div class="col-md-4"></div>
			<div class="col-md-4">
				<h1>Inscription</h1>
				<?php
				if($success == 0)
					echo '<div class="alert alert-danger" role="alert">Cette e-mail est déjà utilisée</div>';
				?>
				<div class="form-group">
					<label for="exampleInputNom">Nom</label>
					<?php echo $this->formInput($form->get('real_name')); ?>
					<!--<input type="nom" class="form-control" id="exampleInputNom" placeholder="Nom">-->
				</div>
			</div>
			<div class="col-md-4"></div>
		</div>
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="exampleInputEmail1">Adresse mail</label>
					<?php echo $this->formInput($form->get('email')); ?>
					<!--<input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">-->
				</div>
			</div>
			<div class="col-md-4"></div>
		</div>
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="exampleInputPassword1">Mot de passe</label>
					<?php echo $this->formInput($form->get('password')); ?>
					<!--<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Mot de passe">-->
				</div>
			</div>
			<div class="col-md-4"></div>
		</div>
		<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="exampleInputPassword2">Retapez le mot de passe</label>
					<?php echo $this->formInput($form->get('repassword')); ?>
					<!--<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Retaper-le">-->
				</div>
			</div>
			<div class="col-md-4"></div>
		</div>
		<div class="col-md-4"></div>
		<div class="col-md-4">
			
			<?php echo $this->formInput($form->get('submit')); ?>
			<!--<button type="submit" class="btn btn-primary">S'inscrire</button>-->
		</div>
		<div class="col-md-4"></div></div>
<?php
 echo $this->form()->closeTag();

?>