 <?php
 // module/Sign/view/sign/sign/add.phtml:

  $this->headTitle("Inscription");


 $form->setAttribute('action', $this->url('sign', array('action' => 'index')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 
 
?>
		<div class="row">

			<div class="col-md-4"></div>
			<div class="col-md-4">
			
				<div class=" panel panel-default bs-callout bs-callout-primary">

					<div class="panel-body">
					
					
				<h1>Inscription</h1>
				<?php
				if(!$email_available)
					echo '<div class="alert alert-danger" role="alert">Cette e-mail est déjà utilisée</div>';
				if(!$nickname_available)
					echo '<div class="alert alert-danger" role="alert">Ce pseudo est déjà utilisé</div>';
				?>
				<div class="form-group">
					<label for="exampleInputNom">Pseudo </label>
					<?php echo $this->formInput($form->get('real_name')); ?>
				</div>
				<div class="form-group">	
				<i>Composé de lettres ou chiffres uniquement</i>
				</div>
				<div class="form-group">
					<label for="exampleInputEmail1">Adresse mail</label>
					<?php echo $this->formInput($form->get('email')); ?>
				</div>				
				
				<div class="form-group">
					<label for="exampleInputPassword1">Mot de passe</label>
					<?php echo $this->formInput($form->get('password')); ?>
				</div>				
				<div class="form-group">	
				<i>6 caractères minimum</i>
				</div>				
				<div class="form-group">
					<label for="exampleInputPassword2">Retapez le mot de passe</label>
					<?php echo $this->formInput($form->get('repassword')); ?>
				</div>				
				
				<?php echo $this->formInput($form->get('submit')); ?>				
				
				
				</div>
				</div>
				
			</div>
			<div class="col-md-4"></div>
		</div>

<?php
 echo $this->form()->closeTag();

?>